import type { CmsBlock } from "../types";
import type { PageBySlugQuery } from "../generated/graphql";

// The seam: WPGraphQL-for-ACF flexible-content union (__typename) → CmsBlock
// { layout, data }. Block props are decoupled from the transport — the whole
// point of the boundary (workflow/02). Per-block field names already match the
// zod schemas because the query aliases camelCase → snake_case (and unique
// repeater names back to the block prop name, e.g. `items: faqItems`).

type PageNode = NonNullable<PageBySlugQuery["page"]>;
// Block list items are nullable in the live 2.x schema — strip null for the union.
type BlockNode = NonNullable<NonNullable<NonNullable<PageNode["pageFields"]>["blocks"]>[number]>;

// wpgraphql-acf 2.x type name → ACF layout / registry key. Exhaustive by construction
// (Record over the union of __typename literals) — adding a block won't typecheck until it's
// mapped here. GENERATED by scripts/migrate-blocks-2x.mjs (the live SDL is the source).
const LAYOUT: Record<BlockNode["__typename"], string> = {
  PageFieldsBlocksAuthorBylineLayout: "author_byline",
  PageFieldsBlocksBeforeAfterLayout: "before_after",
  PageFieldsBlocksBentoGridLayout: "bento_grid",
  PageFieldsBlocksCardGridLayout: "card_grid",
  PageFieldsBlocksCaseStudiesLayout: "case_studies",
  PageFieldsBlocksColumnsLayout: "columns",
  PageFieldsBlocksComparisonTableLayout: "comparison_table",
  PageFieldsBlocksContactFormLayout: "contact_form",
  PageFieldsBlocksCtaBannerLayout: "cta_banner",
  PageFieldsBlocksFaqLayout: "faq",
  PageFieldsBlocksFeatureGridLayout: "feature_grid",
  PageFieldsBlocksFeatureRowsLayout: "feature_rows",
  PageFieldsBlocksGalleryLayout: "gallery",
  PageFieldsBlocksHeroLayout: "hero",
  PageFieldsBlocksIntegrationsGridLayout: "integrations_grid",
  PageFieldsBlocksKeyTakeawaysLayout: "key_takeaways",
  PageFieldsBlocksLocationsMapLayout: "locations_map",
  PageFieldsBlocksLogoStripLayout: "logo_strip",
  PageFieldsBlocksMediaTextLayout: "media_text",
  PageFieldsBlocksNewsletterLayout: "newsletter",
  PageFieldsBlocksPostGridLayout: "post_grid",
  PageFieldsBlocksPricingLayout: "pricing",
  PageFieldsBlocksPricingMatrixLayout: "pricing_matrix",
  PageFieldsBlocksProcessStepsLayout: "process_steps",
  PageFieldsBlocksReviewsLayout: "reviews",
  PageFieldsBlocksRichTextLayout: "rich_text",
  PageFieldsBlocksServicesGridLayout: "services_grid",
  PageFieldsBlocksStatWithSourceLayout: "stat_with_source",
  PageFieldsBlocksStatsBandLayout: "stats_band",
  PageFieldsBlocksTabbedContentLayout: "tabbed_content",
  PageFieldsBlocksTeamLayout: "team",
  PageFieldsBlocksTimelineLayout: "timeline",
  PageFieldsBlocksTocLayout: "toc",
  PageFieldsBlocksUspBarLayout: "usp_bar",
  PageFieldsBlocksVideoLayout: "video",
  PageFieldsBlocksVideoTestimonialLayout: "video_testimonial",
};

// wpgraphql-acf 2.x exposes ACF image fields as a connection EDGE (`image { node { … } }`).
// Flatten any `{ node: … }` wrapper so blocks keep reading a plain `image.sourceUrl` (the
// zod shape). Safe + generic: ACF edges are the only single-`node`-keyed objects in block
// data (repeaters are arrays; groups have multiple keys). HQ FRICTION #98.
function flattenEdges(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(flattenEdges);
  if (value && typeof value === "object") {
    const keys = Object.keys(value);
    if (keys.length === 1 && keys[0] === "node") return flattenEdges((value as { node: unknown }).node);
    return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, flattenEdges(v)]));
  }
  return value;
}

export function toBlocks(
  blocks: NonNullable<PageNode["pageFields"]>["blocks"] | null | undefined,
): CmsBlock[] {
  if (!blocks) return [];
  return blocks.flatMap((node) => {
    if (!node) return [];
    const { __typename, ...data } = node;
    return [{ layout: LAYOUT[__typename], data: flattenEdges(data) as Record<string, unknown> }];
  });
}
